### ISSUE TITLE
Time-out issue with large sample

### ISSUE THREAD

**Issue by isabella33g** [PennLINC/ModelArray#86]
Hello!

I am trying to fit a linear model with ModelArray.lm but am struggling with the time limit required for the model to run. I am analysing the data on a supercomputer with 32 CPUs per task, 50G memory and 3-day time limit, but my job keeps going over the maximum time. 
I am wondering if you have any intuition of how long this should take to run in a large sample size (n=1074) with 3 covariates (age, ICV, sex), or whether there is something unusual with my code or data?

I've attached screenshots of my R-script that contains the linear model and the bash file I use to run the R-script - please let me know if theres anything else that might help

Thanks in advance!
Best wishes,
Isabella

![run_lm_fdc_SH_script](https://github.com/PennLINC/ModelArray/assets/124648085/3d82bcad-b9d9-4299-afb9-463b98b8f44e)
![run_lm_fdc_R_script](https://github.com/PennLINC/ModelArray/assets/124648085/a4b0bebd-a79c-4b00-a02e-db9a4cd42d5d)

**Comment by zhao-cy** [comment]
Hi @isabella33g ! Thanks for submitting this issue. It sounds like you're only fitting linear models and it shouldn't take such long time. I'm curious if you could successfully run through the example walkthrough - specifically, using, say 4 CPUs and running through all elements (instead of the first 100 or so). It should only take several hours. If it takes more than a day, please let me know.

Also, for any time-out jobs, could you please let us know the printed messages? You may quote them with tripple backticks (see [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)), if that's easier than taking screenshots. I'm curious which step it reached and if there was any error messages.

Finally, when calling the R script to run, i.e., your bash script line 20, I think I used a different way. If that's of your concern, the way I used was like [this](https://github.com/PennLINC/ModelArray_paper/blob/main/benchmarks/benchmark_ModelArray.lm.sh#L66). The command I used can also save the printed messages into a text file.

Thanks,
Chenying

**Comment by isabella33g** [comment]
Hi Chenying,

I just ran through the example walkthrough with the data provided and it all worked okay - took 1.5hrs and finished with no errors.
I also attempted to run my original script for 7 days and it still timed out so must be something going wrong! For the timed out jobs, the error file has this printed message:
```
Fitting element-wise linear models for FDC
initiating....
looping across elements....
slurmstepd: error: *** JOB 59553895 ON spartan-bm113 CANCELLED AT 2024-05-22T11:10:09 DUE TO TIME LIMIT ***
```

And the output file has this printed message: 
``` 

R version 4.2.1 (2022-06-23) -- "Funny-Looking Kid"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> # Load model array package
> library(ModelArray)
> # Set working directory
> setwd("/data/scratch/projects/punim1678/data/template/model_array_wholebrain")
> 
> ## Will start with FDC
> metric = "FDC"
> 
> # Create a ModelArray class object
> h5_path <- "wholebrain_fdc.h5" #filename of fixel-wise data (.h5 file)
> modelarray <- ModelArray(h5_path, scalar_types = c("FDC"))
> phenotypes <- read.csv("/data/gpfs/projects/punim1678/IMAGEN/jobs/wholebrain_tractography/model_array/IMAGEN_phenotypes_fdc.csv") # Load cohort phenotype csv
> 
> # Make sure gender (categorical variable) is a factor)
> phenotypes$sex_binary <- factor(phenotypes$sex_binary)
> 
> ## Full linear Model
> # Formula for linear model between FDC and CAPE with age and gender as covariates (going to ignore recruitment centre for now)
> formula.lm_fdc <- FDC ~ CAPE_zscore + age_zscore + ICV_zscore + sex_binary
> # Run a full linear model on all fixels
> run.lm_fdc <- ModelArray.lm(formula.lm_fdc, modelarray, phenotypes, "FDC", n_cores = 32)
subset: default 
weights: default 
na.action: default 
method: default 
model: default 
x: default 
y: default 
qr: default 
singular.ok: default 
contrasts: default 
offset: default 
```

Thank you for your suggestin to run the R script that way! I tested it out this way and its helpful that it saves the output into a textfile. 

Thanks,
Isabella

**Comment by zhao-cy** [comment]
Hi @isabella33g , it's good to hear that the example walkthrough finished without error. Then let's focus on your goal here. I'm suspecting if something is using more resources than you requested. For example, using more CPUs will require more memory - see figures in our ModelArray paper. You requested 32 CPUs which is a lot. So I'm curious if your job can run through with 4 CPUs and 50 GB of memory. It should not take too long to finish - I think it's still be within a day. If you still hope to use a lot of CPUs, please try increasing the amount of memory you requested.

Based on the printed messages you sent me (which are quite helpful here), it looks like ModelArray hasn't started the stat fitting yet before the error occurred. Therefore another thing you might try is just to run first 100 or 1000 elements, to see if the error will rise again, before you try the full run.

Let me know how it goes.

Thanks,
Chenying

**Comment by isabella33g** [comment]
Hi Chenying, thanks for the suggestions! I've tried running the job with 4 CPUs and 50 GB memory (I also specified n_cores=4 in the Rscript). I tested this out with the full model _and_ a subset of 100 elements (with element.subset = 1:100). Both of these jobs are still running after 24 hours and the output files look the same as they do above. 
Its very strange... I've tested out the model with a subset of 100 elements on the terminal (rather than in the script) and this seems to run fine:
```
run.lm_fdc <- ModelArray.lm(formula.lm_fdc, modelarray, phenotypes, "FDC", element.subset = 1:100, n_cores = 4)

Fitting element-wise linear models for FDC
initiating....
looping across elements....
  |=======================================================| 100%, Elapsed 00:07
```
Please let me know if you have any other suggestions!
Thanks,
Isabella

**Comment by zhao-cy** [comment]
Hi @isabella33g ! Sorry for the late response. If I understand correctly, with your data, running directly in the terminal using interactive nodes of the cluster is fine, but running as a job using compute nodes of the cluster fails. If this is the case, I suspect the job is using more resouces than you requested, or some setups of the cluster job you specified were not very well. I know some clusters may have some weird configurations you have to correctly set up to make sure the job runs through. You might talk to the IT person of the cluster you're using to see why the job fails, or if any setup config is missing.

In the meantime, you might try running ModelArray fittings on your laptop or workstation - i.e., a supercomputer/cluster might not be needed, if you use limited CPUs (say 4 CPUs), so that it won't use too much memory. You might play with the number of CPUs (e.g., lowering it) if you have extremely limited memory on your computer. I don't suggest directly running in the terminal on the supercomputer/cluster for the full set of elements, as you'll occupy interactive node resources (CPUs etc) for a couple of hours, and it will affect other people's use.

Let me know how it goes.

Thanks,
Chenying

**Comment by isabella33g** [comment]
Hi Chenying,

I tried running the full model on my laptop rather than supercomputer and it finally worked!! Must've been somehting to do with the resoure allocation. Thanks so much for all your help :)

Thanks,
Isabella

**Comment by zhao-cy** [comment]
Whoohoo! So glad it works!! 

Cheers,
Chenying
